@Shows.Api_HostAddress = http://localhost:1338

GET {{Shows.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
POST http://localhost:1338/api/shows
Content-Type: application/json

{
    "name":"Twin Peaks the Return of",
    "description":"David Lynch at his best",
    "streamingService":"Amazon Prime"
}
###
GET http://localhost:1338/api/shows/{d6482dde-6158-437a-849e-2d11d30732d8}
Accept: application/json