@Shows.Api_HostAddress = http://localhost:5432

POST http://localhost:5432/api/shows
Content-Type: application/json

{
    "name":"Sneaky Pete",
    "description":"Dark Humor",
    "streamingService":"Netflix"
}

###
